# yml 파일 작성할 때는 : 뒤에 꼭 한 칸을 띄워야 한다.
name: testback deployment

# event에 해당
on:
  push:
    branches: ["main"]

# event가 발생할 때 동작하는 내용
jobs:
  build:
    # name은 형식이 따로 없다.(comment 같은 느낌)
    name: testback build & deploy
    # ubuntu의 최신 버전을 사용하겠다는 의미
    runs-on: ubuntu-latest

    steps:
      - name: github action
        run: echo "github action"

      - name: hello
        run: echo "hello world"

      # 여러가지를 실행시키고 싶을 때는 run: 뒤에 |를 작성한 후 실행할 작업들을 작성해준다
      - name: git hello
        run: |
          echo "git hello"
          echo "hello world"
